orbs:
  aws-eks: circleci/aws-eks@1.1.0
version: 2.1
jobs:
 helm-chart-deploy:
  steps: 
    - checkout
    - aws-eks/install-helm-chart:
        context:
          - dummy-helm
        chart: stable/kong
        cluster-name: my-cluster
        release-name: dummy-app-release

workflows:
  deployment:
    jobs:
      - helm-chart-deploy