orbs:
  aws-eks: circleci/aws-eks@1.1.0
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/install-helm-chart:
          context:
            - dummy-helm
          chart: ./dummy-app
          cluster-name: my-cluster
          release-name: dummy-app-release