orbs:
  aws-eks: circleci/aws-eks@0.2.3
version: 2.1
workflows:
  deployment:
    jobs:
      - aws-eks/install-helm-chart:
          chart: ./chart/dummy-app
          cluster-name: my-cluster
          release-name: dummy-app-release